#default environment
spring:
  profiles:
    active: dev
#multi environments
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atlantis?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456frank
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:  # 设置multipart上传文件大小限制
      max-file-size: 7MB  # 单个文件最大值
      max-request-size: 14MB  # 总上传文件最大和值
      enabled: true

server:
  port: 8081
  # 内网ip, 部署后填入外网ip
  address: localhost

mybatis:
  mapper-locations: classpath:com/atlantis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# page helper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

atlantis:
#  需要改成相对路径
  photosBasePath: D:\OneDrive - mail.dlut.edu.cn\Workspace\AtlantisFiles\Data\photos\
  articlePicturesBasePath: D:\OneDrive - mail.dlut.edu.cn\Workspace\AtlantisFiles\Data\article_pictures\

---
# 生产环境，开发完毕后进行重新配置

spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atlantis?serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456frank
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:  # 设置multipart上传文件大小限制
      max-file-size: 7MB  # 单个文件最大值
      max-request-size: 14MB  # 总上传文件最大和值
      enabled: true

server:
  port: 8686

mybatis:
  mapper-locations: classpath:com.atlantis.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

atlantis:
  #  需要改成相对路径
  userphotoBasepath: D:\OneDrive - mail.dlut.edu.cn\Workspace\atlantis-back\Data\userphotos
---
